;; (package-initialize)

(add-to-list 'load-path "~/.emacs.d/lisp")

;; Package Management
;; -----------------------------------------------------------------
(require 'init-packages)
(require 'init-better-defaults)
;; (require 'init-evil)
(require 'init-org)
(require 'init-general)
(require 'init-ein)
(require 'init-ibuffer)
(require 'init-magit)
(require 'init-ido)
(require 'init-iedit)
(require 'init-ivy)
(require 'init-projectile)
;; (require 'init-python)
(require 'init-python-lsp)
(require 'init-ranger)
(require 'init-shell)
(require 'init-smex)
(require 'init-keybindings)
(require 'init-winum)
(require 'init-yasnippet)
(require 'neotree_icons)
(require 'treemacs)
(require 'init-ui)

